audio:
  target_sample_rate: 16000
  chunk_seconds: 0.6
  input_device: null
asr:
  model: paraformer-zh-streaming
  device: cuda
  chunk_size:
  - 0
  - 10
  - 5
  encoder_chunk_look_back: 4
  decoder_chunk_look_back: 1
  disable_update: true
  punc_model: ct-punc
ui:
  font_family: MiSans VF Medium
  font_size: 38
  window_opacity: 0.87
  max_chars: 20000
  theme: light
  always_on_top: true
  win_x: 2456
  win_y: 1880
  win_w: 1344
  win_h: 246
  close_action: ask
  toolbar_hide_delay_ms: 800
  lock_scroll_to_bottom: true
  min_win_w: 480
  min_win_h: 120
